### ISSUE TITLE
Building iOS to a real device fails

### ISSUE THREAD

**Issue by raghavyadavm** [mikehardy/rnfbdemo#10]
When building the rnfbdemo project to real iOS device it fails with the below error
```
Link folly
ld: -U and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by raghavyadavm** [comment]
I created a new project using 69.1 and got the same error on a real device
```
1. npx react-native init RN --version=0.69.1
2. Enabled Hermes and use_frameworks in podfile
3. Build on a real iOS device
```

Error
![image](https://user-images.githubusercontent.com/8011402/176503499-007fd7ec-49ca-4b0c-a8df-8a24cee79b9e.png)

**Comment by mikehardy** [comment]
Turns out (from the related PR on react-native) that this may always be incompatible with bitcode *but* apparently bitcode is deprecated in Xcode 14 anyway. So, it is perhaps best to simply disable it, then there's no problem. In Podfile in postinstall this will do it, I will probably update make-demo.sh to do this when I get a chance

```ruby
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
```

**Comment by raghavyadavm** [comment]
Great thanks for the workaround. I will update my project with these settings

**Comment by raghavyadavm** [comment]
Disabling Bitcode started giving me errors with other libraries like Reanimated. I ended up using framework with the option `use_frameworks! :linkage => :static` and it solved the problem

**Comment by mikehardy** [comment]
Yes - other libraries may have issues as well, it really is a big change, thanks for reporting what worked, that will help me and others going forward!

**Comment by raghavyadavm** [comment]
I create a PR to update the demo.sh with the above changes https://github.com/mikehardy/rnfbdemo/pull/11

**Comment by raghavyadavm** [comment]
Unfortunately, the release builds are failing with these errors. I had to disable the Hermes for use_frameworks to work 
![image](https://user-images.githubusercontent.com/8011402/177673887-37d98e84-4949-4cd8-852c-c5240cf7c542.png)

**Comment by ptreitler** [comment]
> Turns out (from the related PR on react-native) that this may always be incompatible with bitcode _but_ apparently bitcode is deprecated in Xcode 14 anyway. So, it is perhaps best to simply disable it, then there's no problem. In Podfile in postinstall this will do it, I will probably update make-demo.sh to do this when I get a chance
> 
> ```ruby
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>     end
>   end
> ```

This workaround solved the issue for me, but I also had to disable Bitcode for release builds in my project's XCode config.

**Comment by mikehardy** [comment]
@ptreitler 

> but I also had to disable Bitcode for release builds in my project's XCode config

Hmm - perhaps instead of `target.build_configurations.each` it needs to be broader, more like this one?

https://github.com/mikehardy/rnfbdemo/blob/041c1699d9bf9ce94147b54f9051bb5e4bcc6ec4/make-demo.sh#L202

@raghavyadavm text of error messages vs images are strongly preferred if possible, I'm traveling and mobile right now most of the time so images are rough on me to see all pinch+zoom :-) - it might be best to post that in the react-native main repo as it looks like you've stumbled on "the next thing..." after getting the basic build+link to work. Hopefully it's an easy fix - you might try pinging @kudo as he was the creator of the original fix that made Hermes build at all (the first, important step) and the error may be familiar to them, or...it could be aware from areas any of us are familiar with :sweat_smile:

**Comment by Kudo** [comment]
hi there!

sorry being late for this response. i finally get a chance to investigate this problem and it turns out to me that `use_frameworks! + hermes` is not supported from day one.

the root cause is that due to React-Core podspec does not have a dependency to React-hermes, so here [the import](https://github.com/facebook/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/React/CxxBridge/RCTCxxBridge.mm#L43-L49) is not available. and the runtime is jsc but not hermes. 

i need some time to think a proper solution for the issue. just to update my investigation here.

**Comment by mikehardy** [comment]
I always appreciate your investigations and efforts @Kudo - thanks for even trying, sincerely. I posted something related here on the road to 0.70 discussion - https://github.com/reactwg/react-native-releases/discussions/26#discussioncomment-3166350

I've exposed the issue in this script (at least) by adding exposure of the `__jsiExecutorDescription` variable on this branch where I am playing with things: 

- expose hermes vs jsc: https://github.com/mikehardy/rnfbdemo/commit/b0ac801c7025e8d2d8b1ee29d7b7804c4ead2f7f
- branch where I am playing with properly turning on hermes on 0.69.1 - https://github.com/mikehardy/rnfbdemo/commits/rn0.69.1

**Comment by Kudo** [comment]
nice finding for it's jsc not hermes by the `__jsiExecutorDescription`. i proposed a pr in https://github.com/facebook/react-native/pull/34222 let's see how do people think for this approach.

**Comment by maxmandia** [comment]
> > Turns out (from the related PR on react-native) that this may always be incompatible with bitcode _but_ apparently bitcode is deprecated in Xcode 14 anyway. So, it is perhaps best to simply disable it, then there's no problem. In Podfile in postinstall this will do it, I will probably update make-demo.sh to do this when I get a chance
> > ```ruby
> >   installer.pods_project.targets.each do |target|
> >     target.build_configurations.each do |config|
> >       config.build_settings['ENABLE_BITCODE'] = 'NO'
> >     end
> >   end
> > ```
> 
> This workaround solved the issue for me, but I also had to disable Bitcode for release builds in my project's XCode config.

This worked for me too :)

**Comment by karladler** [comment]
I tried all of the solutions mentioned above, but still no luck.
My Version is RN 69.3
