### ISSUE TITLE
Is it posibble to run firebase V7 in RN 059.10?

### ISSUE THREAD

**Issue by krisnailafat** [mikehardy/rnfbdemo#4]
im wondering Is it posibble to run firebase V7 in RN 059.10?

**Comment by mikehardy** [comment]
Some people do it, but it's not supported because running anything below react-native 0.60 is not a good idea at this point and it's been more than a year. Yes I know that upgrade (from 59 to 60) is really painful so I do empathize

Check the issues in the react-native-firebase repository there are some success reports with manual linking, probably with 'v6' in the text vs v7 though (the work will be the same though)

**Comment by krisnailafat** [comment]
thank you for the response, i am agree the change from 59 to 60 its so painful and i dont want to that now
i did it using latest rnfirebase with RN 59.
this is the step what I do
- install firebase, manual linking
- install jetifier, run it
- `android.useAndroidX=true
android.enableJetifier=true` in gradle.properties
- `xmlns:tools="http://schemas.android.com/tools"` in top androidmanifest and `tools:replace="android:appComponentFactory"
      android:appComponentFactory="whateverString"` in <application
thats it
and now im going to try in iphone
